# Generated by Django 6.0.2 on 2026-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_obj', models.CharField(db_index=True, max_length=100)),
                ('target_obj', models.CharField(db_index=True, max_length=100)),
                ('target_group', models.IntegerField()),
            ],
            options={
                'unique_together': {('source_obj', 'target_obj')},
            },
        ),
    ]
