# Generated by Django 6.0.2 on 2026-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=100, unique=True)),
                ('ticket_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
