# Generated by Django 6.0.2 on 2026-03-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticketmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation', models.CharField(db_index=True, max_length=128)),
                ('request_id', models.CharField(db_index=True, default='-', max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
