# Generated by Django 6.0.2 on 2026-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_llm_usage_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, default='-', max_length=128)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('obj_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('abap_code', models.TextField(blank=True)),
                ('requirement_spec', models.TextField(blank=True)),
                ('ai_result', models.TextField()),
                ('streamed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeployReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, default='-', max_length=128)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_input', models.TextField(blank=True)),
                ('selected_trs', models.JSONField(blank=True, default=list)),
                ('final_report', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
